name: Deploy

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Emotion_Detection_CV  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker build -t faroukdaboussi0/motion_detection:latest .

      - name: Install Railway CLI
        run: |
          curl -sSL https://railway.app/install.sh | sh

      - name: Print Railway Token
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          echo "RAILWAY_TOKEN is $RAILWAY_TOKEN"

      - name: Log in to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway login

      - name: Deploy to Railway
        run: |
          railway up --docker
